jobs:
- job: 'backup'
  displayName: 'Backup Wiki'
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - checkout: none
  - task: Bash@3
    displayName: 'Check Pipeline Variables'
    inputs:
      failOnStderr: true
      targetType: 'inline'
      script: |
        if [ -z "$KUBE_CONTEXT" ]; then >&2 echo 'Variable "KUBE_CONTEXT" is not set'; fi
        if [ -z "$WIKI_NAMSPACE" ]; then >&2 echo 'Variable "WIKI_NAMSPACE" is not set'; fi
        if [ -z "$MYSQL_APP_LABEL" ]; then >&2 echo 'Variable "MYSQL_APP_LABEL" is not set'; fi
        if [ -z "$BOOKSTACK_APP_LABEL" ]; then >&2 echo 'Variable "BOOKSTACK_APP_LABEL" is not set'; fi
  - task: Bash@3
    displayName: 'Print Tool Version'
    inputs:
      failOnStderr: false
      targetType: 'inline'
      script: |
        command -v az
        az version
        command -v kubectl
        kubectl version --client=true
  - task: Bash@3
    displayName: 'Download Backup Script'
    inputs:
      failOnStderr: true
      targetType: 'inline'
      script: curl -s https://raw.githubusercontent.com/pacroy/bookstack-backup/master/backup.sh -o backup.sh
  - task: Bash@3
    displayName: 'Execute Backup Script'
    inputs:
      failOnStderr: true
      targetType: 'filePath'
      filePath: backup.sh